Refactored a whole bunch of stuff to make WorldContactListeners easy …
Jonas-C/TDT4240-Gaalf pull request #50
Opened 2020-04-09 19:38 UTC by Jonas-C

…to use. This allowed for a refactoring of the goal system as well, allowing for several players to finish at different times. Also implemented stroke-outs, with a max limit of 12 strokes per level. Furthermore, also made it easier to implement water/lava/death zones later on.

2020-04-09 20:32 UTC, Brogzybro approved these changes

2020-04-10 11:41 UTC, Trulsmatias commented on core/src/com/gaalf/game/ecs/system/GoalSystem.java
> +//        }
May just remove this?

2020-04-10 11:50 UTC, Trulsmatias requested changes
There are some changes that needs to be made, but I think it is easier to see when my PR is accepted. So just wait for that. I will create it very soon

2020-04-10 14:11 UTC, Trulsmatias approved these changes

2020-04-10 14:13 UTC, Trulsmatias commented
There were some problems with my other PR. I will not have time to work on that until tomorrow. So I think it is better to just approve this PR, and then fix the issue in my other PR later. So that this is not blocking things.

2020-04-11 00:18 UTC, merged