Feat/1 multiplayer
Jonas-C/TDT4240-Gaalf pull request #54
Opened 2020-04-13 14:26 UTC by Jonas-C

First iteration of multiplayer. Although somewhat unpredictable I think it's ready to be merged. UI can be improved further-on but it'd be nice to use display names for MP as opposed to randomly generated names.

2020-04-14 12:23 UTC, Brogzybro commented
ser ut til å fungere bra, E litt kluss med at ballane ikkje e heilt synca. Begge når mål på eine skjermen, men ikkje på den andre.

2020-04-14 13:23 UTC, mchyll commented
Forslag til enkel fiks av sync-issues: Når en spiller sender et ballslag inkluderer den også posisjonen sin, sånn at alle andre spillere oppdaterer posisjonen til den ballen hos seg når de mottar ballslag-eventet. På den måten blir hver enkelt spiller "source of truth" for sin egen balls posisjon.
Blir åpenbart potensielt store hopp dersom posisjonene har havnet veldig ute av sync, men jeg mener det er en veldig enkel fiks som kan funke foreløpig.

2020-04-14 13:33 UTC, Jonas-C commented
> Forslag til enkel fiks av sync-issues: Når en spiller sender et ballslag inkluderer den også posisjonen sin, sånn at alle andre spillere oppdaterer posisjonen til den ballen hos seg når de mottar ballslag-eventet. På den måten blir hver enkelt spiller "source of truth" for sin egen balls posisjon.
> Blir åpenbart potensielt store hopp dersom posisjonene har havnet veldig ute av sync, men jeg mener det er en veldig enkel fiks som kan funke foreløpig.

Dette kan være en god løsning som ikke krever altfor mye arbeid. En annen løsning er å la balllene stanse fullstendig før man skyter igjen. Etter å satt world-stepping til et fast timestep er distansene ballene flyr mer eller mindre helt like på tvers av instanser, problemer oppstår i hovedsak når det er store endringer i velocity (og by extension, posisjon) og ballen skytes igjen.

2020-04-14 18:38 UTC, Trulsmatias requested changes
List of servers does not appear on the screen when using an emulator (Pixel 2).

2020-04-14 21:10 UTC, Jonas-C commented
@Trulsmatias You just need to uninstall and re-install the application. It has to do with kryo and its required permissions. Nothing to do with the code really

2020-04-15 10:31 UTC, Trulsmatias reviewed
Yes, works now hehe. There are still some problems like not telling the player og their opponent when they are finished. But I am not sure if that fix should be in another pull request?

2020-04-15 14:57 UTC, mchyll approved these changes

2020-04-15 15:29 UTC, Trulsmatias approved these changes

2020-04-15 15:30 UTC, Trulsmatias commented
> Yes, works now hehe. There are still some problems like not telling the player og their opponent when they are finished. But I am not sure if that fix should be in another pull request?

Will indeed be fixed in another pull request

2020-04-15 16:46 UTC, merged