Simplified factories for player entities
Jonas-C/TDT4240-Gaalf pull request #56
Opened 2020-04-14 17:52 UTC by Trulsmatias

Also moved factories and their objects inside the ecs package as it a part of the ecs.

After going down a rabbit hole about creational patterns I came to the conclusion that no pattern was needed. The simplest way was just with a static simple factory class since no instantiation was needed as the factory object is only used once. 

Closes issues #42 and #41

2020-04-14 21:21 UTC, Jonas-C requested changes

2020-04-14 21:21 UTC, Jonas-C commented on core/src/com/gaalf/presenter/BaseGamePresenter.java
> +    private Entity createShotIndicator(PlayerInfo player){
This function could be removed. It's only used at line 156, and it's not really needed there anymore.

2020-04-14 21:21 UTC, Jonas-C commented on android/assets/shotIndicators/shotIndicators.atlas
> +Excalibur
You use "Excalibur" some places but "Filled white shot indicator" other places. If this is going to be implemented as a setting consistency would save us a headache later-on

2020-04-16 11:46 UTC, Trulsmatias commented
Had some problems merging in the changes from master on multiplayer. Closing this and creating a new pull request when this is finished

2020-04-16 11:46 UTC, closed without merging